# This workflow will build and push a new build file to sandbox server

name: CI - Deploy Frontend - TTE to gh-pages

on:
  push:
    branches:
      - 'main'
      

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy Enviornment Files
      id: copy-env
      run: |
        mv .env.development .env.production

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.17
    - name: Install Packages
      run: npm install
      
    - name: Set Token
      uses: actions/labeler@v2  
      with:
        repo-token: ${{ secrets.GH_TOKEN }}

    - name: Build Static Files
      run: CI=false npm run electron-production
      
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist
